INSERT INTO account_types (id, name)
VALUES (1, 'Guest'),
       (2, 'Normal User'),
       (3, ''),
       (4, ''),
       (5, ''),
       (6, ''),
       (7, 'Admin');

INSERT INTO preferences (name, type)
VALUES ('Dairy', 'allergen'),
       ('Eggs', 'allergen'),
       ('Gluten', 'allergen'),
       ('Grain', 'allergen'),
       ('Peanuts', 'allergen'),
       ('Seafood', 'allergen'),
       ('Sesame', 'allergen'),
       ('Shellfish', 'allergen'),
       ('Soy', 'allergen'),
       ('Sulfite', 'allergen'),
       ('Tree Nut', 'allergen'),
       ('Wheat', 'allergen');

INSERT INTO preferences (name, type)
VALUES ('Gluten Free', 'diet'),
       ('Keto', 'diet'),
       ('Vegetarian', 'diet'),
       ('Lacto-Vegetarian', 'diet'),
       ('Ovo-Vegetarian', 'diet'),
       ('Vegan', 'diet'),
       ('Pescetarian', 'diet'),
       ('Paleo', 'diet'),
       ('Primal', 'diet'),
       ('Low FODMAP', 'diet'),
       ('Whole30', 'diet');

INSERT INTO searchTerms (name, type)
VALUES ('main course', 'type'),
       ('side dish', 'type'),
       ('dessert', 'type'),
       ('appetizer', 'type'),
       ('salad', 'type'),
       ('bread', 'type'),
       ('breakfast', 'type'),
       ('soup', 'type'),
       ('beverage', 'type'),
       ('sauce', 'type'),
       ('marinade', 'type'),
       ('fingerfood', 'type'),
       ('snack', 'type'),
       ('drink', 'type');

INSERT INTO searchTerms (name, type)
VALUES ('African', 'cuisine'),
       ('Asian', 'cuisine'),
       ('American', 'cuisine'),
       ('British', 'cuisine'),
       ('Cajun', 'cuisine'),
       ('Caribbean', 'cuisine'),
       ('Chinese', 'cuisine'),
       ('Eastern European', 'cuisine'),
       ('European', 'cuisine'),
       ('French', 'cuisine'),
       ('German', 'cuisine'),
       ('Greek', 'cuisine'),
       ('Indian', 'cuisine'),
       ('Irish', 'cuisine'),
       ('Italian', 'cuisine'),
       ('Japanese', 'cuisine'),
       ('Jewish', 'cuisine'),
       ('Korean', 'cuisine'),
       ('Latin American', 'cuisine'),
       ('Mediterranean', 'cuisine'),
       ('Mexican', 'cuisine'),
       ('Middle Eastern', 'cuisine'),
       ('Nordic', 'cuisine'),
       ('Southern', 'cuisine'),
       ('Spanish', 'cuisine'),
       ('Thai', 'cuisine'),
       ('Vietnamese', 'cuisine');